---
# ansible-playbook -i provision/scaleworks provision/configure_host.yml
- hosts: all
  become: true
  gather_facts: yes
  vars:
    additional_disks:
      - disk: /dev/sdb
        fstype: ext4
        mount_options: defaults
        mount: /data
    docker_opts: "-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375"
    # docker_opts: "-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --registry-mirror=http://{{ hostvars[groups['repository'][0]]['ansible_host'] }}:5000 --insecure-registry={{ hostvars[groups['repository'][0]]['ansible_host'] }}:5000"
    docker_registries:
      - host: "https://index.docker.io/v1/"
        auth: "dGlhbnlhd3k6cjB5czFuZ2g0bQ=="
        email: "tianya_wy@homtail.com"
      # - host: "http://{{ hostvars[groups['repository'][0]]['ansible_host'] }}:5000/"
      #   auth: "Zmx5MndpbmQ6cHdjNTAycg=="
      #   email: "fly2wind@gmail.com"
      # - host: "reg.dev.twleansw.com"
      #   auth: "YWRtaW46TGVhbnN3ZGV2MQ=="
      #   email: "admin@admin.com"
    # docker_additonal_directory: /data/lib/docker
  roles:
    - common
    - docker
