---
# master playbook
- name: Deploy infrastructure
  hosts: all
  vars:
   dbname: "data-db"
   dbPort: "5436"
   superUserPassword: "r0ys1ngh4m"
   vaultname: "vault-dev"
   vaultVolume: ./vault-volume
  tasks:
    - name: Ensure docker-compose directory exists
      file:
        path: ./infrastructure
        state: directory

    - name: Ensure docker-compose file is up to date
      template:
        src: infrastructure-docker-compose.j2
        dest: "./infrastructure/docker-compose.yml"

    - name: docker-compose up to build infrastructure
      docker_service:
        project_name: infrastructure
        project_src: ./infrastructure
        remove_volumes: yes
        state: absent

    - name: Ensure vault volumes exists
      file:
        path: "{{vaultVolume}}"
        state: absent
