---
# master playbook
- name: Deploy infrastructure
  hosts: all
  tasks:
    - name: Ensure docker-compose directory exists
      file:
        path: "{{infrastructureDockerComposeFolder}}"
        state: directory

    - name: Ensure docker-compose file is up to date
      template:
        src: infrastructure-docker-compose.j2
        dest: "{{infrastructureDockerComposeFolder}}/docker-compose.yml"

    - name: docker-compose up to build infrastructure
      docker_service:
        project_name: infrastructure
        project_src: "{{infrastructureDockerComposeFolder}}"
        remove_volumes: yes
        state: absent

    - name: Ensure vault volumes exists
      file:
        path: "{{vaultVolume}}"
        state: absent
