---
# master playbook
- name: Deploy infrastructure
  hosts: all
  roles:
    - {role: provision, action_type: "install"}

  tasks:
    - name: pip install psycopg2
      pip:
        name: psycopg2
        state: present
      become: True

    - name: crate vault user
      postgresql_user:
        name: "{{dbInstanceOwner}}"
        password: "{{vaultUserPassword}}"
        port: "{{dbPort}}"
        login_host: "{{ansible_default_ipv4.address}}"
        login_password: "{{superUserPassword}}"

    - name: create vaultdb
      postgresql_db:
        name: "{{dbInstanceName}}"
        owner: "{{dbInstanceOwner}}"
        port: "{{dbPort}}"
        login_host: "{{ansible_default_ipv4.address}}"
        login_password: "{{superUserPassword}}"

    - name: GRANT ALL PRIVILEGES
      postgresql_privs:
        db: "{{dbInstanceName}}"
        privs: ALL
        type: database
        role: "{{dbInstanceOwner}}"
        port: "{{dbPort}}"
        login_host: "{{ansible_default_ipv4.address}}"
        login_password: "{{superUserPassword}}"

    # - name: Copy vault init script
    #   tempfile:
    #     state: directory
    #     suffix: vault
    #   register: vaultScriptPath

    - name: Copy vault init script
      copy:
        src: vault-init.sh
        dest: "./vault-init.sh"

    - name: Vault init
      command: sh "./vault-init.sh" {{vaultname}} {{vaultServer}}
