---
# master playbook
- name: Deploy infrastructure
  hosts: all
  vars:
   dbname: "data-db"
  tasks:
    - name: Ensure docker-compose directory exists
      file:
        path: ./infrastructure
        state: directory

    - name: Ensure docker-compose file is up to date
      template:
        src: docker-compose.j2
        dest: "./infrastructure/docker-compose.yml"

    - name: docker-compose up to build infrastructure
      docker_service:
        project_name: infrastructure
        project_src: ./infrastructure
        # state: present
        # remove_volumes: yes

    - name: wait-for-db-restart
      action: command docker exec {{dbname}} pg_isready
      register: db_logs
      until: db_logs.stdout.find("/var/run/postgresql:5432 - accepting connections") != -1
      retries: 5
      delay: 10
