---
- name: install common package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - ca-certificates
    - apt-transport-https
    - software-properties-common
