---
- name: "config {{ ansible_distribution|lower }} system"
  include: "config/{{ ansible_os_family|lower }}.yml"

- name: configure system authorizedkey
  authorized_key:
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    user: root
  become: yes

- name: configure system hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: configure system hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
  become: yes
